[package]
name = "powerclip-tauri"
version = "0.1.0"
description = "PowerClip - Clipboard Manager"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "macos-private-api", "tray-icon", "image", "image-png"] }
tauri-plugin-shell = "2"
global-hotkey = "0.5"
rusqlite = "0.31"
chrono = "0.4"
md5 = "0.7"
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
